/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.example.java-application-conventions")
}

javaApplication {
    dependencies {
        implementation("org.apache.commons:commons-text")
        implementation(project(":utilities"))
    }
    mainClass = "com.example.app.App"
}
