/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    `jvm-test-suite`
}

testing {
    suites {
        // Configure the built-in test suite
        withType<JvmTestSuite>().configureEach {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.10.0")
        }
    }
}
