/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gradle.experimental.settings;

import org.gradle.api.Plugin;
import org.gradle.api.initialization.Settings;
import org.gradle.api.model.ObjectFactory;
import org.gradle.experimental.settings.internal.DefaultWorkspaceSettings;

import javax.inject.Inject;
import java.io.File;

/**
 * A plugin that allows you to configure the workspace settings.
 */
public abstract class WorkspaceSettingsPlugin implements Plugin<Settings> {
    public void apply(Settings settings) {
        settings.getExtensions().create("workspace", DefaultWorkspaceSettings.class, settings);
    }
}
