/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    id("com.example.java-testing-common-conventions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}
