/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("com.example.java-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    id("orggradle.experiments.javaapplication")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}
// Maybe this would actually be a platform dependency:
//dependencies {
//    implementation(platform(project(":platform")))
//    implementation(platform("org:platform:1.0"))
//}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.10.0")
    }
}