name: Delete preview on PR close
on:
  pull_request:
    types: [closed]

jobs:
  delete_preview:
    runs-on: ubuntu-20.04
    env:
      PR_PATH: ${{ github.event.repository.name }}/pull/${{github.event.number}}
      DOMAIN: gradle.github.io
      PREVIEW_REPO: community-site-preview

    permissions:
      pull-requests: write
      id-token: write

    steps:
      - name: make empty dir
        run: mkdir public

      - name: delete folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PREVIEW_DEPLOYMENT_KEY }}
          external_repository: gradle/${{ env.PREVIEW_REPO }}
          publish_dir: ./public
          destination_dir: ${{ env.PR_PATH }}

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::992382829881:role/GHASecrets_declarative-gradle_all
          aws-region: "eu-central-1"
      - name: Get secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            BOT_GRADLE_GITHUB_TOKEN, gha/declarative-gradle/_all/BOT_GRADLE_GITHUB_TOKEN

      - name: Comment on PR
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.BOT_GRADLE_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: > 
            🪓 PR closed, deleted preview at https://github.com/${{ env.PREVIEW_REPO }}/tree/gh-pages/${{ env.PR_PATH }}/
